#!/bin/bash

GITREV=$(git describe --tags $(git rev-list --tags --max-count=1))

make clean
make

mkdir -p release/_DEBUG
cp *.bin release/
gunzip *.gz
cp stage2.elf32 release/
cp stage2.elf release/_DEBUG/
cp AUTHORS release/
cp CHANGELOG release/
cp README release/

cd release
tar czvf XeLL_Reloaded-2stages-${GITREV}.tar.gz *
mv *.tar.gz ..
cd ..
rm -rf release

make clean
